//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendCash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public long TransactionDetailId { get; set; }
        public Nullable<long> TransactionId { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverAccountNumber { get; set; }
        public string ReceiverBankName { get; set; }
        public long TransactionAmount { get; set; }
        public bool isApproved { get; set; }
        public bool isComplete { get; set; }
        public Nullable<System.DateTime> CompleteDt { get; set; }
    
        public virtual TransactionHeader TransactionHeader { get; set; }
    }
}
